### ISSUE TITLE
undeclared dependency on File::Which [rt.cpan.org #69250]

### ISSUE THREAD

**Issue by xdg** [cpan-testers/CPAN-Reporter#63] opened 2016-04-03 17:49 UTC
https://rt.cpan.org/Ticket/Display.html?id=69250

    rkitover@hlagh ~ % perl -MCPAN::Reporter -le 1
    Can't locate File/Which.pm in @INC (@INC contains: /etc/perl
    /usr/local/lib/perl/5.12.4 /usr/local/share/perl/5.12.4 /usr/lib/perl5
    /usr/share/perl5 /usr/lib/perl/5.12 /usr/share/perl/5.12
    /usr/local/lib/site_perl /home/rkitover) at
    /usr/share/perl5/File/HomeDir.pm line 10.
    BEGIN failed--compilation aborted at /usr/share/perl5/File/HomeDir.pm
    line 10.
    Compilation failed in require at
    /usr/local/share/perl/5.12.4/CPAN/Reporter.pm line 23.
    BEGIN failed--compilation aborted at
    /usr/local/share/perl/5.12.4/CPAN/Reporter.pm line 23.
    Compilation failed in require.
    BEGIN failed--compilation aborted.

**Comment by garu** [comment] 2016-04-21 17:40
Odd. File::Which is a [named dependency of File::HomeDir](https://metacpan.org/source/ADAMK/File-HomeDir-1.00/Makefile.PL#L10), which is a [named dependency of CPAN::Reporter](https://metacpan.org/source/DAGOLDEN/CPAN-Reporter-1.2017/Makefile.PL#L33). I couldn't find any older version of File::HomeDir which did not properly required File::Which :/

This looks like a strange issue, and I can't reproduce it on a clean install. I'm going to close it and if someone ever manages to do it again, we'll revisit.

**Closed by garu** 2016-04-21 17:40 UTC
